USE ROLE SECURITYADMIN; -- or ACCOUNTADMIN / whoever owns the agent

-- 1. Grant access to the parent database and schema
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE CORTEX_LLM_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE CORTEX_LLM_ROLE;

-- 2. Grant the ability to use the specific Agent
GRANT USAGE ON AGENT SNOWFLAKE_INTELLIGENCE.AGENTS.NIELSE_AGENT TO ROLE CORTEX_LLM_ROLE;

USE ROLE SECURITYADMIN;

-- 1. Grant access to the database
GRANT USAGE ON DATABASE DEV_SNOWFLAKE_DB TO ROLE CORTEX_LLM_ROLE;

-- 2. Grant access to the schemas
GRANT USAGE ON SCHEMA DEV_SNOWFLAKE_DB.BRONZE TO ROLE CORTEX_LLM_ROLE;
GRANT USAGE ON SCHEMA DEV_SNOWFLAKE_DB.SILVER TO ROLE CORTEX_LLM_ROLE;
GRANT USAGE ON SCHEMA DEV_SNOWFLAKE_DB.GOLD TO ROLE CORTEX_LLM_ROLE;

-- BRONZE
GRANT SELECT ON ALL TABLES IN SCHEMA DEV_SNOWFLAKE_DB.BRONZE TO ROLE CORTEX_LLM_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DEV_SNOWFLAKE_DB.BRONZE TO ROLE CORTEX_LLM_ROLE;

-- SILVER
GRANT SELECT ON ALL TABLES IN SCHEMA DEV_SNOWFLAKE_DB.SILVER TO ROLE CORTEX_LLM_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DEV_SNOWFLAKE_DB.SILVER TO ROLE CORTEX_LLM_ROLE;

-- GOLD
GRANT SELECT ON ALL TABLES IN SCHEMA DEV_SNOWFLAKE_DB.GOLD TO ROLE CORTEX_LLM_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DEV_SNOWFLAKE_DB.GOLD TO ROLE CORTEX_LLM_ROLE;

USE ROLE SECURITYADMIN;

-- BRONZE
GRANT SELECT ON ALL SEMANTIC VIEWS IN SCHEMA DEV_SNOWFLAKE_DB.BRONZE TO ROLE CORTEX_LLM_ROLE;

-- SILVER
GRANT SELECT ON ALL SEMANTIC VIEWS IN SCHEMA DEV_SNOWFLAKE_DB.SILVER TO ROLE CORTEX_LLM_ROLE;

-- GOLD
GRANT SELECT ON ALL SEMANTIC VIEWS IN SCHEMA DEV_SNOWFLAKE_DB.GOLD TO ROLE CORTEX_LLM_ROLE;